version: "3.3"
services:
  etcd1:
    image: quay.io/coreos/etcd:v3.5.9
    restart: always
    container_name: "etcd1"
    volumes:
      - etcd1:/var/lib/etcd
      - ./ssl:/etc/etcd/ssl
      - ./conf/etcd1.conf:/etc/etcd/etcd.conf
    command: /usr/local/bin/etcd --config-file /etc/etcd/etcd.conf
    ports:
      - 2379:2379
      - 2380:2380

  etcd2:
    image: quay.io/coreos/etcd:v3.5.9
    restart: always
    container_name: "etcd2"
    volumes:
      - etcd2:/var/lib/etcd
      - ./ssl:/etc/etcd/ssl
      - ./conf/etcd2.conf:/etc/etcd/etcd.conf
    command: /usr/local/bin/etcd --config-file /etc/etcd/etcd.conf
    ports:
      - 2381:2381
      - 2382:2382

  etcd3:
    image: quay.io/coreos/etcd:v3.5.9
    restart: always
    container_name: "etcd3"
    volumes:
      - etcd3:/var/lib/etcd
      - ./ssl:/etc/etcd/ssl
      - ./conf/etcd3.conf:/etc/etcd/etcd.conf
    command: /usr/local/bin/etcd --config-file /etc/etcd/etcd.conf
    ports:
      - 2383:2383
      - 2384:2384

  cli:
    image: bamboofirewall/cli:v0.0.1
    container_name: "cli"
    depends_on:
      - etcd1
      - etcd2
      - etcd3
    environment:
      - ETCDCTL_ENDPOINTS=https://etcd1:2379,https://etcd2:2381,https://etcd3:2383
      - ETCDCTL_CACERT=/etc/etcd/ssl/ca.pem
      - ETCDCTL_CERT=/etc/etcd/ssl/etcd.pem
      - ETCDCTL_KEY=/etc/etcd/ssl/etcd-key.pem
      - ETCDCTL_API=3
      - ETCD_ROOT_PASSWORD=change_me
      - ETCD_BAMBOOFW_PASSWORD=bamboofw_change_me_now
      - ETCD_BAMBOOFW_USER=bamboofw
    volumes:
      - ./ssl:/etc/etcd/ssl
      - ./conf/calicoctl.cfg:/etc/calico/calicoctl.cfg
      - ./bbfw/:/bamboofw/demo
    command: tail -f /dev/null

  clisetup:
    image: bamboofirewall/cli:v0.0.1
    container_name: "clisetup"
    restart: "no"
    depends_on:
      - etcd1
      - etcd2
      - etcd3
    environment:
      - ETCDCTL_ENDPOINTS=https://etcd1:2379,https://etcd2:2381,https://etcd3:2383
      - ETCDCTL_CACERT=/etc/etcd/ssl/ca.pem
      - ETCDCTL_CERT=/etc/etcd/ssl/etcd.pem
      - ETCDCTL_KEY=/etc/etcd/ssl/etcd-key.pem
      - ETCDCTL_API=3
      - ETCD_ROOT_PASSWORD=change_me
      - ETCD_BAMBOOFW_PASSWORD=bamboofw_change_me_now
      - ETCD_BAMBOOFW_USER=bamboofw
    volumes:
      - ./ssl:/etc/etcd/ssl
      - ./conf/calicoctl.cfg:/etc/calico/calicoctl.cfg
    entrypoint: [ "bash", "-c", "/bamboofw/etcd-init-auth.sh"]  

  mongodb:
    image: mongo:6.0-jammy
    restart: always
    depends_on:
      - etcd1
      - etcd2
      - etcd3
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: change_me
      MONGO_INITDB_DATABASE: bamboofw
    container_name: "mongodb"
    volumes:
      - mongodb:/data/db

  watcher:
    image: bamboofirewall/watcher:v0.0.2
    restart: always
    depends_on:
      - mongodb
    container_name: "watcher"
    environment:
      - BAMBOOFW_APP_ENV=testing
      - BAMBOOFW_ENABLE_DEBUG_MODE=true
      - BAMBOOFW_ETCD_PEER_URLS=https://etcd1:2379 https://etcd2:2381 https://etcd3:2383
      - BAMBOOFW_ETCD_CA_CERT=LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJ5RENDQVc2Z0F3SUJBZ0lVVE5zb21TNk9kMkhnbElRWmZpaCtxTEdnRGZzd0NnWUlLb1pJemowRUF3SXcKUWpFTE1Ba0dBMVVFQmhNQ1ZrNHhEekFOQmdOVkJBZ1RCa2hoSUU1dmFURUxNQWtHQTFVRUJ4TUNTRTR4RlRBVApCZ05WQkFNVERHVjBZMlF0WTJ4MWMzUmxjakFlRncweU16QTRNREl3T1RNeU1EQmFGdzB5T0RBM016RXdPVE15Ck1EQmFNRUl4Q3pBSkJnTlZCQVlUQWxaT01ROHdEUVlEVlFRSUV3WklZU0JPYjJreEN6QUpCZ05WQkFjVEFraE8KTVJVd0V3WURWUVFERXd4bGRHTmtMV05zZFhOMFpYSXdXVEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndOQwpBQVNjWWszU2hsdjNsZFJGMU9qWmdpVW9kSFBBWHZOZlVpdk11WW9RZVhJTjcwWEVkVHgzbE5LN2V0ZWVLU1l3CmZZN0RCRGtSc3NLWVRsNFVaVHZUdEhIOG8wSXdRREFPQmdOVkhROEJBZjhFQkFNQ0FRWXdEd1lEVlIwVEFRSC8KQkFVd0F3RUIvekFkQmdOVkhRNEVGZ1FVcUY4MzZITmlIQ01pcTNEcEwvT1dpTUlPaWFJd0NnWUlLb1pJemowRQpBd0lEU0FBd1JRSWhBSjFTeFQrRmlCRHgvRGhneldvRmFobHRLdGxkaGdSRmFUOWUvcDlIaHJiZkFpQWF3ZzRxCnVMZDNMaHBtQjFsQXVyU3hCZ1JuWXVjWjBtaWNJOG5iRVRqUUdnPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
      - BAMBOOFW_ETCD_SERVER_CERT=LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN6VENDQW5PZ0F3SUJBZ0lVVHlSeGg5ck95enl6TndPWDY3ZDRleUlIK3ljd0NnWUlLb1pJemowRUF3SXcKUWpFTE1Ba0dBMVVFQmhNQ1ZrNHhEekFOQmdOVkJBZ1RCa2hoSUU1dmFURUxNQWtHQTFVRUJ4TUNTRTR4RlRBVApCZ05WQkFNVERHVjBZMlF0WTJ4MWMzUmxjakFlRncweU16QTRNREl4TURFek1EQmFGdzB6TXpBM016QXhNREV6Ck1EQmFNQmN4RlRBVEJnTlZCQU1UREdWMFkyUXRZMngxYzNSbGNqQ0NBU0l3RFFZSktvWklodmNOQVFFQkJRQUQKZ2dFUEFEQ0NBUW9DZ2dFQkFKWnpCLzhmWnBwZHRTaTM3T25kUE9PbUhrcnJOZkE3QW1FcDNpQjE3U1EzVERsSwo2TGNFVTZJck1ZQlhVLzBmVjJ3ak5Fc2hzZVRnQ1B0VWRYdUtCUUk4cFlQLzVCVEhwMXdTQng2a05FdEhSQzB2Cm1QMThkNFdWb1FycEJBb3lUME1GUW0wQm5nK2VlVnVTZmFMUCtZWUszWU1FTlBBajlGL1JoZDJCd3JtZzZVZGwKSHIrRTFnaHlKenRsMEkwK2ZaMDd1anFXTmVPTjUwME5Jajh4dXgwbll1ZkFwb2l5bTkvdVoyUVgxalRUM1UrZApmcy9adFN2YnNMdDhJcWp2dy9USDVMLzFxT0JuQlUzaTh4UEQ5aFRmTFNmU2VnbTRaYXNocWxVaWRrUEYzR21DCmxYa1Brd3Jid1JrMlBUQU00MTNSblY5bi8rNkNtZWxESTFaTlNEc0NBd0VBQWFPQnBqQ0JvekFPQmdOVkhROEIKQWY4RUJBTUNCYUF3SFFZRFZSMGxCQll3RkFZSUt3WUJCUVVIQXdFR0NDc0dBUVVGQndNQ01Bd0dBMVVkRXdFQgovd1FDTUFBd0hRWURWUjBPQkJZRUZNQ29tMUwyY3pBMDl4MmU2UlVxb0ZVcGNmTDFNQjhHQTFVZEl3UVlNQmFBCkZLaGZOK2h6WWh3aklxdHc2Uy96bG9qQ0RvbWlNQ1FHQTFVZEVRUWRNQnVDQldWMFkyUXhnZ1ZsZEdOa01vSUYKWlhSalpET0hCSDhBQUFFd0NnWUlLb1pJemowRUF3SURTQUF3UlFJaEFKNUV3NmhlNVFTUTYyL3JJczNBTDMvNQpoSWJXSlIrRWx6Q1Y2QlNibmNJa0FpQmo4dnFhVUFCcUdtVXFoS0JoSHJyZGxXY1RZUkQwODYyWU1GNDIwa29SCk5nPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
      - BAMBOOFW_ETCD_SERVER_KEY=LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcEFJQkFBS0NBUUVBbG5NSC94OW1tbDIxS0xmczZkMDg0NlllU3VzMThEc0NZU25lSUhYdEpEZE1PVXJvCnR3UlRvaXN4Z0ZkVC9SOVhiQ00wU3lHeDVPQUkrMVIxZTRvRkFqeWxnLy9rRk1lblhCSUhIcVEwUzBkRUxTK1kKL1h4M2haV2hDdWtFQ2pKUFF3VkNiUUdlRDU1NVc1Sjlvcy81aGdyZGd3UTA4Q1AwWDlHRjNZSEN1YURwUjJVZQp2NFRXQ0hJbk8yWFFqVDU5blR1Nk9wWTE0NDNuVFEwaVB6RzdIU2RpNThDbWlMS2IzKzVuWkJmV05OUGRUNTErCno5bTFLOXV3dTN3aXFPL0Q5TWZrdi9XbzRHY0ZUZUx6RThQMkZOOHRKOUo2Q2JobHF5R3FWU0oyUThYY2FZS1YKZVErVEN0dkJHVFk5TUF6alhkR2RYMmYvN29LWjZVTWpWazFJT3dJREFRQUJBb0lCQURTOFJZVkx3RzlEZ1lpdwpUNzc1NmFueVJKUUdOblhxZVQ4TnFlcSs2MHpTaFVsZjFJcXlYWTV1alg5ckhPbVEzdGZzenh1MngrQnVGemZoCnR2eUN1SmE4STFoTmpla3F3cU1uUG8rakJ5R0w3WDNaUFVzOUliZ1Zac21vTzk1SEhEbGwwbzdiRGtoelNCNnQKRHBUUFNhdU9pMjZ0UHRFZUNUNjg5cXRhSEtOc0ZrQjFzem9HeCtQdTJNUTR0VE1ZTEZHWUF1eE1taTAza3hQRApvVnZudnlaZTdkZTgydytvdlNZUDJ3UXFCZnZlQTRpQ0V2Z3ZRdWREMUFWSlRzNUlwSWdDaGRjMWo1OWJoOVhrCnFEM0ZuRnlVdmRWbXhFOTFGMGN4NGpLU3o4anVVNkV4TzJyNHI1czNEMG4wbWhBLythSXhkUFdIUTJSaUxQeDAKdkVTMVBPRUNnWUVBeHYvc2JnanFpakIySGh0RVFmVUlPNmxmNmhaYmc3b1pCZEVvdDMyZXVGbFQ1K0VYUDdjegpLazF1R0g5OTRUN2hEZ2hETkhrU3EzMUdIY1dLR0dOYVlpenFIWGlrcHl5WjI3RndIMm85TWk2MWFWWGhBSHMwCm85Z0tnQTBvU1huazVIeTR0dlZLUVJtUUVrNlRRditzN1hnZ0ZlQVd2Q0lwdjJQbUNKMTlnODBDZ1lFQXdZc00KbU5MWGJ1VVBNZzZCMDBuVS85T2dZekc5dU1pU3lidDQxN1NBVEtYN1NOa3FCRXkxU0U3cHJJQ2JGNGZZaERxcwoyZGs2QW02NGt2NHRYcWlqTnJhSmE0V1loUU5Wbm1KbnRCNnlNL3U1dzFtM0Q2bjFONWRZZjRGaFFNTHlLeVhzCjVpMzE5K1p2RjhHNC8yVVY1aGZhQTRUakVBeW5IU0g4RGVtYkJDY0NnWUVBaDdrZzdlTlM0N0V0dmxibWRQM0UKQWIwQlY4eXIyZW5oQ3lDZVhwZGsyMkxCWVZNWjRqRDJ5cEZJMTVpTXFFV1VoVmVKVG82TTl6MVh4eEpsbjBDVAo4b1dqbnpvYlFwR2Uxa0hzc09CcW9JRk81V3JYTE5iYkRpeFk3UUVNU3lEQnhqeHlWd1p4QUhtSTA1T1h5SWhNCnp5R3c4SHFIeHdTZDZKVWYzUnhjOExrQ2dZQk9vYkdTZlVhdGRUNkJOY2VsRWdBSmwrODNuY1BZeVJScUJWS0oKUUhwSHFiKzN6eEwxQUQwK2pXRCtocGw4SytMWmhnVW4xTXR1cFpFemx6VFRtbXdGRkpBc01QRFFTWlNGYnJGMwpTbWxZR1ZOVmZLT1ZKNVhLNmlBNFhWWW51NHdyMzVLcHljNSswdzRiZHNjMGE5dER5amoyNlF4ZlB1UytQMHBxClZKaDRUUUtCZ1FDUnp2REY5a0FnOWNSYVJLaWJsdndoZ0pzZ2pCY2VDY1NNeFptS2RCZnpLc2w1U0ltQzk2Z3kKV3BUKzdqTmYvazN4UmZOZGNuc3R1a3YrVG1BY3VxUnVNa082bXFhMXNmTy9RT1JpM214aUlXZURxMGozWlFTcwp6QnorcGJpZ2FBQ3U1WXA4MjJ6Z21vU3cyVmRMWDl6R0lkdjVweWl4cEtSVWVQdUpxcE1DcVE9PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=
      - BAMBOOFW_ETCD_USERNAME=bamboofw
      - BAMBOOFW_ETCD_PASSWORD=bamboofw_change_me_now
      - BAMBOOFW_ETCD_WATCHER_PATH=/calico/resources/v3/projectcalico.org
      - BAMBOOFW_MONGODB_NAME=bamboofw
      - BAMBOOFW_MONGODB_URI=mongodb://root:change_me@mongodb:27017/?authSource=admin

  be:
    image: bamboofirewall/be:v0.0.2
    restart: always
    depends_on:
      - mongodb
    container_name: "be"
    environment:
      - ACCESS_TOKEN_EXPIRY_HOUR=2
      - ACCESS_TOKEN_SECRET=change_me
      - ADMIN_PASSWORD=change_me
      - APP_ENV=release
      - CONTEXT_TIMEOUT=2
      - DB_NAME=bamboofw
      - MONGO_URI=mongodb://root:change_me@mongodb:27017/?authSource=admin
      - PORT=9091
      - REFRESH_TOKEN_EXPIRY_HOUR=168
      - REFRESH_TOKEN_SECRET=change_me
      - SERVER_ADDRESS=:9091
    ports:
      - 9091:9091

  besetup:
    image: bamboofirewall/be:v0.0.2
    restart: "no"
    depends_on:
      - mongodb
    container_name: "besetup"
    environment:
      - ACCESS_TOKEN_EXPIRY_HOUR=2
      - ACCESS_TOKEN_SECRET=change_me
      - ADMIN_PASSWORD=change_me
      - APP_ENV=release
      - CONTEXT_TIMEOUT=2
      - DB_NAME=bamboofw
      - MONGO_URI=mongodb://root:change_me@mongodb:27017/?authSource=admin
      - PORT=9091
      - REFRESH_TOKEN_EXPIRY_HOUR=168
      - REFRESH_TOKEN_SECRET=change_me
      - SERVER_ADDRESS=:9091
    entrypoint: [ "/app/create_admin"]  

  fe:
    image: bamboofirewall/fe:v0.0.2
    restart: always
    container_name: "fe"
    depends_on:
      - be
    environment:
      - NEXT_PUBLIC_APP_URL=http://DEMO_IP:3000/
      - NEXT_PUBLIC_BAMBOO_API_URL=http://DEMO_IP:9091
    ports:
      - 3000:3000

volumes:
  mongodb:
  etcd1:
  etcd2:
  etcd3:
