apiVersion: projectcalico.org/v3
kind: GlobalNetworkPolicy
metadata:
  name: 'db-example'
spec:
  selector: ((role == 'db') && (project == 'example'))
  ingress:
    - action: Allow
      protocol: TCP
      source:
        selector: ((role == 'app') && (project == 'example'))
      destination:
        ports: [3306]
    - action: Allow
      protocol: TCP
      source:
        selector: ((role == 'db') && (project == 'example'))
      destination:
        ports: [3306]      
  egress:
    - action: Allow
      protocol: TCP
      source:
        selector: ((role == 'db') && (project == 'example'))
      destination:
        selector: ((role == 'db') && (project == 'example'))
        ports: [3306]
