apiVersion: projectcalico.org/v3
kind: HostEndpoint
metadata:
  name: 192.168.56.11
  labels:
    role: lb
    zone: black
    namespace: production
    project: example
    ip: 192.168.56.11
spec:
  node: lb01
  interfaceName: eth1
  expectedIPs: ["192.168.56.11"]
